name = "club-lambda"
main = "worker.js"
compatibility_date = "2026-06-27"

routes = [
  { pattern = "virajrao.com/gamble*", zone_name = "virajrao.com" },
  { pattern = "virajrao.com/clublambda*", zone_name = "virajrao.com" }
]

[[rules]]
type = "Text"
globs = ["index.html", "app-css.txt", "app-client.txt"]
fallthrough = true
